### ISSUE TITLE
Add LICENSE file to the repository

### ISSUE THREAD

**Issue by janlindblom** [diepala/cantor#1]
Right now, there is no mention of which license the source falls under, if any. It would be nice if you would add a proper license so that there are no question marks for anyone building upon your work! See [foostan/crkbd](https://github.com/foostan/crkbd/blob/main/LICENSE) or [TweetyDaBird/Lotus58](https://github.com/TweetyDaBird/Lotus58/blob/v1.11/LICENSE) license for example.

**Comment by diepala** [comment]
Thanks for the advice. I have added a license.
