### ISSUE TITLE
Wireless technically possible?

### ISSUE THREAD

**Issue by kekscode** [diepala/cantor#10]
Hello 👋
Long time corne low profile user here. I recently built a corne with ZMK firmware and nice!nano v2 MCU and don’t want to go back having canbles.

I love your pcb design (especially the stagger) and the diodeless approach. Do you think it is possible build a wireless variant of the cantor?

**Comment by diepala** [comment]
You would need a blackpill with bluetooth support, but I don't know if that exists.

**Comment by kekscode** [comment]
Maybe not (yet?). I‘ll build a cantor this weekend and if it suits me i will do some research. Kudos for the simple design. I am looking at the pcbs right now and i like the KISS approach a lot 👍

**Comment by azzamsa** [comment]
@kekscode any update? I love to have the wireless version too.

**Comment by kekscode** [comment]
Not really feasible at the moment.

**Comment by funkycode** [comment]
I would assume it is with https://mechwild.com/product/pillbug/
Blackpill compatible with BLE and ZMK support
