### ISSUE TITLE
Firmware needed

### ISSUE THREAD

**Issue by tangbonze** [diepala/cantor#12]
Hello there:
I'm new to spilt keyboard. Your design is awesome and perfectly fits my needs.
Just a quick question, where can I find the firmware? I searched for qmk but no luck.
Please advise. thanks.

**Comment by ArthurSonzogni** [comment]
The PR is not merged yet, but you can download it yourself.

I fetched:
https://github.com/qmk/qmk_firmware/pull/16552

```bash
cd ~
git clone https://github.com/qmk/qmk_firmware
cd qmk_firmware
git remote add diepala https://github.com/diepala/qmk_firmware
git fetch diepala
git checkout diepala/cantor
make cantor:default:flash
```

**Comment by diepala** [comment]
There is also vial support. Check [this](https://github.com/vial-kb/vial-qmk/pull/141).
