### ISSUE TITLE
Pin for determining left/right side

### ISSUE THREAD

**Issue by dariogoetz** [diepala/cantor#13]
Is there a pin that is grounded for one of the blackpills and not for the other? It would allow determining if an instance of the firmware runs on the left or right half.

I wrote a keyberon-based firmware for the cantor, where I would like to use such a pin. The firmware can be found here: https://github.com/dariogoetz/cantor-firmware-keyberon

**Comment by diepala** [comment]
There is no pin grounded on one side but not in the other. I thought of it when designing the keyboard, but that was incompatible (or at least hard to achieve) with a reversible PCB.

**Comment by dariogoetz** [comment]
If I understand the pcb correctly, there are two footprints for the MCU. One is used for the left half and the other for the right one. Is it not possible to ground one pin (e.g. A9) only for the one of the two footprints? Am I missing something?
