### ISSUE TITLE
Build with pro-micro compatible with bottom pins? 

### ISSUE THREAD

**Issue by mankoff** [diepala/cantor#22]
Could this board be built with an Elite-C or RP2040 Elite-Pi MCU that has the extra 5 pins on the bottom? Something like this:

 https://d33wubrfki0l68.cloudfront.net/d42e46a6982528aa7328b87dc758414ebabc5dbf/22e62/assets/images/elite-pi_pinout-both-49caa4613444b03c72bc0c06bd622835.png

Or does the black pill provide something extra ?

**Comment by diepala** [comment]
I originally wanted to create the keyboard with the rp2040, but it did not had qmk support.
