### ISSUE TITLE
MCU Orientation

### ISSUE THREAD

**Issue by fla-t** [diepala/cantor#28]
I have ordered a cantor PCB, and just waiting for the switches to be built. I noticed that you have heavily said that the controller must be face up. 

But, in the PCB I noticed that there are 2 Pin arrays, It seems like they are mirror opposite of each other. Meaning I don't need to face down the PCB if I choose the one that has a square white mask around it.

My question is am I right? 

Sorry if it doesn't feel like an issue, because I have no other way to ask this.

**Comment by diepala** [comment]
As it was originally designed, the microcontroller should be soldered on the white mask face down as shown:

![image](https://github.com/diepala/cantor/assets/25749629/0e371c01-2df2-4ff6-8f41-ebcc63a77c61)

But you are right in that it can be soldered face up on the other row of holes.

**Comment by fla-t** [comment]
Thank you so much, I think I should update the docs a little bit.
