### ISSUE TITLE
Add Cantor to splitKbCompare

### ISSUE THREAD

**Issue by azzamsa** [diepala/cantor#3]
Hi.

Would you like to  add this to https://github.com/jhelvy/splitKbCompare :)

Would like to compare to other keyboard. Especially [Torn](https://github.com/rtitmuss/torn).

**Comment by diepala** [comment]
I will take a look on how to do it when I have time. Meanwhile, you can see how the switches are layed out with kiCad.

**Comment by azzamsa** [comment]
Related: https://github.com/jhelvy/splitKbCompare/issues/84

**Comment by azzamsa** [comment]
In case anyone want to print the layout (without installing the KiCad):

![keyboard_pcb-rounded-F_Fab](https://user-images.githubusercontent.com/17734314/170510435-04040cf3-2c02-4cb1-9ee0-767da0ffdbdb.svg)


[cantor.pdf](https://github.com/diepala/cantor/files/8779709/cantor.pdf)

**Comment by l4u** [comment]
It's available at splitKbCompare now.

**Comment by azzamsa** [comment]
> It's available at splitKbCompare now.

Thank you!
