### ISSUE TITLE
Almost nothing works because of wrong Micro Controller?

### ISSUE THREAD

**Issue by xbello** [diepala/cantor#33]
I bought and soldered all the pieces, was able to flash the firmware, and all looked good. But almost no key worked, and the ones that triggered a key press was doing it bad (on repeat, multiple chars, etc).

I tested the soldering with a tester, and noticed that a lot of switches were only conected to the GND. The signal pin was connected to an unconnected hole under the MC, so no surprise they can't trigger a keypress.

On closer inspection, I noticed that my MC is so wide that it had to be soldered *to the outer pins only*, leaving the inner holes disconnected. Your image for the "build guide" where it shows the rubber feet clearly show that the MC uses one of the inner lines of holes and one of the outer lines of holes!

This is what I bought, claims to be a STM32F401CC: https://es.aliexpress.com/item/1005005777418296.html

Finally, the question: *what do I have to search for to ensure the MC has the correct dimensions*?

Thanks!

**Comment by dimipage** [comment]
I have a few STM32 dev boards, and can confirm that there is a bigger footprint on one of them, which does not fit on Cantor. The link you have provided shows the exact dev board that is required, but picture in customers review section displays a bigger one. I assume that the seller does not care about the sizes and have sent you the one which does not fit. 
For example, I have mistakenly ordered from this link https://www.aliexpress.com/item/1005006127461676.html but the seller actually displayed the sizes, so it was all on me. 

And to answer your question, these are the rough dimensions I got from the repo. 
![image](https://github.com/user-attachments/assets/26f185b3-07b0-4d05-893f-4e733745ae37)
So, look for 18mm version. 

Have a good day.
