### ISSUE TITLE
is blackpill STM32F411 compatible

### ISSUE THREAD

**Issue by SppamLite** [diepala/cantor#34]
I'm trying to find blackpill STM32F401CC on aliexpress, but it seems discontinued.

I'm wondering if the WeAct BlackPill STM32F411CEU6 would be compatible, or is there better option out there?

Thanks!

**Comment by diepala** [comment]
It is a more powerful chip, and it should be compatible.

**Comment by SppamLite** [comment]
Thanks for the quick reply!
