### ISSUE TITLE
Release a 36 key Cantor version

### ISSUE THREAD

**Issue by fourstepper** [diepala/cantor#4]
Hi!

A 36 key version of this would be great, are you planning on making this revision?

**Comment by diepala** [comment]
Yes, a 36 key version will be the next variant of the Cantor keyboard. I am waiting to having more feedback on the current version first.

**Comment by stuart-warren** [comment]
Supporting the nice!nano would be amazing with fewer keys if you exclude the trrs

**Comment by stuecklberger** [comment]
FYI: In the meantime someone already created a 36 key version of the Cantor and called it Cantor Remix:

https://github.com/nilokr/cantor-remix

**Comment by Lumi-Eko** [comment]
Maybe you would be interested in the Sweep?
https://github.com/davidphilipbarr/Sweep

**Comment by diepala** [comment]
Fixed by #25
