### ISSUE TITLE
Create a MX compatible version

### ISSUE THREAD

**Issue by twalker** [diepala/cantor#6]
It'd be fantastic to have a version of Cantor that was compatible with MX switches. 

MX compatible hot swap sockets would be ideal IMHO, they:
* Are easier to solder than switches themselves
* Allows exploring different switches

**Comment by diepala** [comment]
I don't have any experience with MX switches, but I think they are taller and potentially more instable without a plate. This problem can be even worse if we add hot swap sockets.
Have you tested or seen other plateless keyboards with the configuration you propose?

**Comment by twalker** [comment]
> Have you tested or seen other plateless keyboards with the configuration you propose?

No, I have not. All the MX compatible keyboards I've built (Corne, Kyria, Sofle, etc) used a base and switch plate. They're quite stable with a case, but I imagine they'd be less stable without one. I'm naively imagining a different version of the PCB with the same layout, with non-choc key spacing, along with switch and base plate designs. If that conflicts with the goals (low cost) of the Cantor, or is impractical, then I totally understand.

**Comment by diepala** [comment]
I don't want a switch plate to be mandatory for the build. The MX keyboard won't be a priority for now, but in the future we could make some tests for MX switches.

**Comment by twalker** [comment]
@diepala , I look forward to any future possibile explorations of an MX version. As a software engineer, I'm not very skilled with electronics or PCB design, but would be happy to be a tester if/when one is needed. Thank you.

**Comment by ratsclub** [comment]
Hmm, I just stumbled upon this issue. I can't really build this keyboard for an affordable price because of its switch... There are some MX compatible switches from Red Dragon that are **really** affordable tho. So I'd be happy to try the MX model if it happens to come out!

**Comment by taurhine** [comment]
This is a great improvement over corne design. It would be awesome to have it with MX switches!

**Comment by artsbentley** [comment]
Yes would love an MX design!

**Comment by diepala** [comment]
Seeing that many people would like this version, I will probably make an MX version.

**Comment by fabikroeger** [comment]
An MX design would be awesome :+1:

**Comment by taurhine** [comment]
or MX Low Profile :heart_eyes: https://www.cherrymx.de/cherry-mx/mx-low-profile/mx-low-profile-red.html

**Comment by mejobloggs** [comment]
Redragon AliExpress has two MX compatible low profile switches... Could be a potentially good option!

https://www.aliexpress.com/item/1005004299855522.html

https://www.aliexpress.com/item/1005003606992057.html

However, I have not used either, so I can't verify if they genuinely are MX compatible

**Comment by albertothedev** [comment]
Any progress on this? I really like the improvements made over CRKBD but the use of Choc switches is a dealbreaker for me, like I'm sure it is for many others.

**Comment by JayceFayne** [comment]
This issue was fixed by #25
