### ISSUE TITLE
Add support for tenting puck

### ISSUE THREAD

**Issue by jbarr21** [diepala/cantor#9]
Would it be possible for you to add support for splitkb's [tenting puck](https://splitkb.com/products/tenting-puck)? This would add to the Comfort aspect of the design philosophy while not hurting the Ease of build since it is optional to use.

**Comment by diepala** [comment]
Not sure how the tenting puck is mounted, but I'll investigate to see if it can be added.

**Comment by leah-splitkb** [comment]
We are currently working on publishing the design files for the splitkb.com tenting puck at https://github.com/splitkb/tenting_puck!

**Comment by chriswill0w** [comment]
any update on this?

**Comment by diepala** [comment]
An MX version of the keyboard is coming in #25 and it has holes for the tenting puck.
